name: 'Preview: build and publish'

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: get node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm i
      - run: PROJECT_PATH=carbon-components npm run build
      - name: Setup Rclone
        uses: AnimMouse/setup-rclone@v1
        with:
          rclone_config: |
            [preview]
            type = s3
            provider = Cloudflare
            access_key_id = ${{ secrets.PREVIEW_ACCESS_KEY_ID }}
            secret_access_key = ${{ secrets.PREVIEW_SECRET_ACCESS_KEY }}
            region = auto
            endpoint = https://${{ secrets.R2_ACCOUNT_ID }}.r2.cloudflarestorage.com
            acl = private
          disable_base64: true
      - run: 'rclone sync build preview:interactive-preview/carbon-components'
